### PR TITLE
Dvorak-mac layout

### PR DESCRIPTION
**Pull request by max-sixty**

### CODE REVIEW

**Comment by farmergreg** [comment]
Great! Could you do a few things for me before I merge your commit:

1) rename the file to m_dvorak.txt in the dvorak folder so that users can activate your layout with prgm+m (m for mac).
2) Add a link in the readme to your work.

Thanks!

**Comment by farmergreg** [comment]
also, please add your name and a license to your work. Something like this will do:

    * ===== Dvorak Mac =====
    *
    * Copyright 2018 by Maxim Lian. Licensed under the MIT License.
    * See LICENSE file in the project root for full license information.

**Comment by farmergreg** [comment]
Thanks again for contributing!

**Comment by max-sixty** [comment]
Thanks for setting up the repo!

**Pull request merged**
